// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSL1f-3vHWP8kBiZj6hPX7U8fvUlDVx9E',
    appId: '1:79273318874:web:baad8fb2e0e7dbb9a988e3',
    messagingSenderId: '79273318874',
    projectId: 'restaurantapplication-83059',
    authDomain: 'restaurantapplication-83059.firebaseapp.com',
    storageBucket: 'restaurantapplication-83059.appspot.com',
    measurementId: 'G-MEEQ1DQDKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeg7DsXeiwHra0OczlDGqVIr8QRKtkMVk',
    appId: '1:79273318874:android:f006ee3d35fd81aca988e3',
    messagingSenderId: '79273318874',
    projectId: 'restaurantapplication-83059',
    storageBucket: 'restaurantapplication-83059.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUdt_6MPvaGGn7Q5rxEKbhU3O0EbpLqZE',
    appId: '1:79273318874:ios:89042a7a99e31af0a988e3',
    messagingSenderId: '79273318874',
    projectId: 'restaurantapplication-83059',
    storageBucket: 'restaurantapplication-83059.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUdt_6MPvaGGn7Q5rxEKbhU3O0EbpLqZE',
    appId: '1:79273318874:ios:14abac925106691ba988e3',
    messagingSenderId: '79273318874',
    projectId: 'restaurantapplication-83059',
    storageBucket: 'restaurantapplication-83059.appspot.com',
    iosBundleId: 'com.example.flutterToDoList.RunnerTests',
  );
}
